# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54765df6b77777352324fd978cd3fb1bebb12a1af6361ee5a7327e2a02d9b0e1ec275388815d32741ba0324392b56d1858493006064c8939210ea002d35bde00

test:
  secret_key_base: 81dcec5d9d8b8ca56241a7e07ef428d479c3963577c7ad7687773b893bc5f115c75357c010e72961fa2b7b378b6a5a677e57e8d68c22eef368a660b52bc17e57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
